# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1M_Egoym2oSv4_QuhOYM6LGYe_sw1BWDh
"""

import seaborn as sns
diamonds=sns.load_dataset('diamonds')
diamonds=diamonds.select_dtypes(include=['float64','int64'])
df=diamonds.copy()
df=df.dropna()
df.head()

import numpy as np
from sklearn.neighbors import LocalOutlierFactor

clf=LocalOutlierFactor(n_neighbors=20,contamination=0.1)

clf.fit_predict(df)

df_scores=clf.negative_outlier_factor_

df_scores[0:10]

np.sort(df_scores)[0:20]  #burada belirlenecek olan bir eşik değere göre işlemler sürdürülür.(sort kçkten büüyüğe sıralama)

esik_deger=np.sort(df_scores)[13]  #bu eşik değer kabul edilip diğer işlemler buna göre gerçekleştirilebilir.

aykiri_tf=df_scores>esik_deger
aykiri_tf

####SiLME Yöntemi

yeni_df=df[df_scores>esik_deger]  #aykırı olmayanm değerlerin hepsi alınmış oldu.
yeni_df

df[df_scores<esik_deger]  #bunlar da aykırı gözlemler

df[df_scores==esik_deger]

####Baskılama Yöntemi

baski_degeri=df[df_scores==esik_deger]
aykirilar=df[~aykiri_tf] 
aykirilar

aykirilar.to_records(index=False) #index değerlerinden kurtulur ve array olur

res=aykirilar.to_records(index=False)
res[:]=baski_degeri.to_records(index=False)  #tüm aykırı derğerlerin yerine baskı değerleri getirilir.
res

df[~aykiri_tf]      #(çok değişkenli bir şekilde aykırı gözlem incelemesi) üst tarafta sonra silme yaklaşımı kullanıldı

import pandas as pd
df[~aykiri_tf] = pd.DataFrame(res, index=df[~aykiri_tf].index)  #buradaki indexi kendimz belirliyoruz yani aykiri_dfin indeksini alıyor.
df[~aykiri_tf]