# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15Ac0srKD_eq2MRYqSSp3J-oJD9Qmc0N9
"""

!pip install missingno

import numpy as np
import pandas as pd
V1=np.array([1,3,6,np.NaN,7,1,np.NaN,9,15])
V2=np.array([7,np.NaN,5,8,12,np.NaN,np.NaN,2,3])
V3=np.array([np.NaN,12,5,6,14,7,np.NaN,2,31])
df=pd.DataFrame(
    {"V1":V1,
     "V2":V2,
     "V3":V3})
df

import missingno as msno   #değişkenlerdeki eksiklik oransal olarak burada ifade edilmiş olur. sağ taraf gözlem sayısı sol taraf yüzdeyi verir
msno.bar(df);

msno.matrix(df); #eksik değerlerin rassallığı ile ilgili soldaki eksen gözlem birimleri boş görünen yerler NaN'dır.

import seaborn as sns
df=sns.load_dataset('planets')
df.head()

df.isnull().sum()

#@title Default title text
msno.matrix(df)

#massteki eksiklikler orbital_perioda bağımlı.

msno.heatmap(df);  #boşluk korelasyonunu verir